[package]
name = "fungus_fighter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy = "0.3.1"
comfy_include_dir = { version = "0.7.3", features = ["glob"] }
